services:
  app:
    image: ticket-metrics:latest
    ports:
      - "9090:9090"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:sqlite:/app/data/database.db
    volumes:
      - ./data:/app/data