spring:
  datasource:
    url: jdbc:sqlite:src/main/resources/sqllite-db/database.db
    driver-class-name: org.sqlite.JDBC

logging:
  level:
    com.shishir.ticketmetrics: DEBUG
#    org.mybatis: DEBUG
#    jdbc.resultset: TRACE
#    jdbc.sqlonly: DEBUG